In [2]:
import pandas as pd
import numpy as np

In [67]:
# curve_df = pd.read_hdf('./data/data_new.h5', key='curve_data')
sample_info = pd.read_hdf('./data/data_new.h5', key='sample_info')
sample_gene = pd.read_hdf('./data/data_new.h5', key='sample_gene')

In [ ]:
curve_df.head()

,well_position,target,dye,amp_score,cq,threshold,baseline_start,baseline_end,cycle_no,rn,drn,Fn,pcr_plate,curve_idx
0,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,1,13408.349609,-49.619302,13408.350,AC00DB2A,183920
1,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,2,13445.377930,-34.252517,13445.378,AC00DB2A,183920
2,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,3,13458.586914,-42.705067,13458.587,AC00DB2A,183920
3,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,4,13539.398438,16.444921,13539.398,AC00DB2A,183920
4,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,5,13588.847656,44.232604,13588.848,AC00DB2A,183920

In [ ]:
sample_gene.head()

  sample_id pcr_plate  target  igi_call      thres_ct
0   S053693  C302JKYE     MS2  Negative  Undetermined
1   S053693  C302JKYE  N gene  Negative  Undetermined
2   S053693  C302JKYE  ORF1ab  Negative  Undetermined
3   S053693  C302JKYE  S gene  Negative  Undetermined
4   S053683  C302JKYF     MS2  Positive    27.3529499

In [ ]:
curve_df_pcr_plate = list(curve_df.pcr_plate.unique())
not_in_sample_info = []
not_in_sample_gene = []
for plate in curve_df_pcr_plate:
    if plate not in sample_info.pcr_plate:
        not_in_sample_info.append(plate)
    if plate not in sample_gene.pcr_plate:
        not_in_sample_gene.append(plate)

In [6]:
# remove rows with empty pcr_plate
sample_info = sample_info.drop(sample_info[sample_info.pcr_plate == ' '].index, axis = 0)

In [ ]:
# remove 'AC00GY53' for having only invalid results

In [75]:
sample_gene = pd.read_csv('./data/sample_gene_2024-02-17.csv')
sample_info = pd.read_csv('./data/sample_info_2024-02-17.csv')

In [31]:
da_result_df = pd.read_hdf('./data/da_result_df.h5', key='da_result_df')

In [3]:
da_result_df.head()

,well_position,target,dye,amp_score,cq,threshold,baseline_start,baseline_end,file
0,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,db2a
1,A1,E gene,VIC,1.641315,UNDETERMINED,6000.0,3,44,db2a
2,A1,N gene,FAM,0.000000,UNDETERMINED,11000.0,3,44,db2a
3,A2,RnaseP,ATTO 647,2.495220,25.078985364948885,10000.0,3,15,db2a
4,A2,E gene,VIC,1.816797,UNDETERMINED,6000.0,3,44,db2a

In [4]:
da_result_df.file.nunique()

1218

In [5]:
amp_df = pd.read_hdf('./data/da_result_df.h5', key='amp_df')
amp_df.head()

  well_position  cycle_no  target            rn        drn  file
0            A1         1  RnaseP  13408.349609 -49.619302  db2a
1            A1         2  RnaseP  13445.377930 -34.252517  db2a
2            A1         3  RnaseP  13458.586914 -42.705067  db2a
3            A1         4  RnaseP  13539.398438  16.444921  db2a
4            A1         5  RnaseP  13588.847656  44.232604  db2a

In [8]:
multcomp_df = pd.read_hdf('./data/da_result_df.h5', key='multcomp_df')

In [76]:
sample_gene['file'] = sample_gene.pcr_plate.apply(lambda x: x.strip()[-4:].lower())

In [74]:
sample_info.head()

,sample_id,sample_barcode,pcr_plate,well_position,sample_type,final_patient_result,current_sample_result,created_date,record_type,retest_sample_id_1,retest_sample_id_2,NA,file
0,S999985,SARS00017970,AC00GXXR,O15,Clinical Sample,Negative,Negative,12/20/21,Submitted Sample,,,gxxr,0gxxr
1,S999984,SARS00024719,AC00GXXR,M15,Clinical Sample,Negative,Negative,12/20/21,Submitted Sample,,,gxxr,0gxxr
2,S999983,SARS00016971,AC00GXXR,E17,Clinical Sample,Positive,Positive,12/20/21,Submitted Sample,,,gxxr,0gxxr
3,S999982,SARS00017463,AC00GXXR,C17,Clinical Sample,Negative,Negative,12/20/21,Submitted Sample,,,gxxr,0gxxr
4,S999981,SARS00024761,AC00GXXR,A17,Clinical Sample,Negative,Negative,12/20/21,Submitted Sample,,,gxxr,0gxxr

In [77]:
amp_fil_unique = amp_df.file.unique()
multcomp_file_unique = multcomp_df.file.unique()
da_file_unique = da_result_df.file.unique()
sample_info_file_unique = sample_info.file.unique()
sample_gene_file_unique = sample_gene.file.unique()
file_not_in_sample_info = []
file_not_in_sample_gene = []
for f in da_file_unique:
    if f not in sample_info_file_unique:
        file_not_in_sample_info.append(f)

    if f not in sample_gene_file_unique:
        file_not_in_sample_gene.append(f)

In [78]:
np.array(file_not_in_sample_gene)

array(['bju_', '382_', 'dc25', 'dcff', 'xze_', 'db15', 'b8u_', 'gy8i',
       '0db6', '0db8', 'gxud', 'dati', 'dc4b', '188_', 'ww_d'],
      dtype='<U4')

In [80]:

np.array(file_not_in_sample_info)

array(['bju_', '382_', 'dc25', 'dcff', 'xze_', 'b8u_', '0db6', '0db8',
       'dati', 'dc4b', '188_', 'ww_d'], dtype='<U4')

In [61]:
sample_gene_plate_unique = sample_gene.pcr_plate.unique()
sample_info_plate_unique = sample_info.pcr_plate.unique()

In [62]:
len(sample_gene_plate_unique), len(sample_info_plate_unique)

(1782, 1633)

In [66]:
# amp_pcr_plate_unique = amp_df.pcr_plate.unique()
# multcomp_pcr_plate_unique = multcomp_df.pcr_plate.unique()
# da_pcr_plate_unique = da_result_df.pcr_plate.unique()
sample_info_pcr_plate_unique = sample_info.pcr_plate.unique()
sample_gene_pcr_plate_unique = sample_gene.pcr_plate.unique()
pcr_plate_not_in_sample_info = []
pcr_plate_not_in_sample_gene = []
for f in da_pcr_plate_unique:
    if f not in sample_info_pcr_plate_unique:
        pcr_plate_not_in_sample_info.append(f)

    if f not in sample_gene_pcr_plate_unique:
        pcr_plate_not_in_sample_gene.append(f)

NameError: name 'da_pcr_plate_unique' is not defined

In [3]:
curve_df = pd.read_hdf('./data/new_data.h5', key='curve_data')
curve_df.head()

,well_position,target,dye,amp_score,cq,threshold,baseline_start,baseline_end,cycle_no,rn,drn,Fn,pcr_plate,curve_idx
0,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,1,13408.349609,-49.619302,13408.350,AC00DB2A,233392
1,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,2,13445.377930,-34.252517,13445.378,AC00DB2A,233392
2,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,3,13458.586914,-42.705067,13458.587,AC00DB2A,233392
3,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,4,13539.398438,16.444921,13539.398,AC00DB2A,233392
4,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,5,13588.847656,44.232604,13588.848,AC00DB2A,233392

In [12]:
print('curve_df shape:', curve_df.shape)
print('Number of pcr_plate in curve_df:', curve_df.pcr_plate.nunique())
print('Number of curves in curve_df:', curve_df.curve_idx.nunique())
curve_df['test_kit'] = (curve_df.groupby(['pcr_plate','well_position']).target.transform('nunique'))
print(curve_df.groupby('test_kit').curve_idx.nunique())

curve_df shape: (59098240, 15)
Number of pcr_plate in curve_df: 1203
Number of curves in curve_df: 1350448
test_kit
3    1016064
4     334384
Name: curve_idx, dtype: int64

In [4]:
sample_info = pd.read_hdf('./data/new_data.h5', key='sample_info')
sample_info.head()

,sample_id,sample_barcode,pcr_plate,well_position,sample_type,final_patient_result,current_sample_result,created_date,record_type,retest_sample_id_1,retest_sample_id_2,file
0,S999985,SARS00017970,AC00GXXR,O15,Clinical Sample,Negative,Negative,12/20/21,Submitted Sample,NaN,NaN,gxxr
1,S999984,SARS00024719,AC00GXXR,M15,Clinical Sample,Negative,Negative,12/20/21,Submitted Sample,NaN,NaN,gxxr
2,S999983,SARS00016971,AC00GXXR,E17,Clinical Sample,Positive,Positive,12/20/21,Submitted Sample,NaN,NaN,gxxr
3,S999982,SARS00017463,AC00GXXR,C17,Clinical Sample,Negative,Negative,12/20/21,Submitted Sample,NaN,NaN,gxxr
4,S999981,SARS00024761,AC00GXXR,A17,Clinical Sample,Negative,Negative,12/20/21,Submitted Sample,NaN,NaN,gxxr

In [15]:
print('Number of pcr_plate in sample_info:', sample_info.pcr_plate.nunique())
print('Number of file in sample_info:', sample_info.file.nunique())
print('Number of samples in sample_info:', sample_info.sample_id.nunique())
print(sample_info.groupby('current_sample_result').sample_id.nunique())
print(sample_info.groupby('final_patient_result').sample_id.nunique())
print(sample_info.groupby('sample_type').sample_id.nunique())

Number of pcr_plate in sample_info: 1598
Number of file in sample_info: 1598
Number of samples in sample_info: 244085
current_sample_result
Inconclusive               2803
Invalid                    8347
Negative                 207958
Positive                  19651
Specimen Insufficient         2
Name: sample_id, dtype: int64
final_patient_result
Negative    205234
Positive     15128
ReSample      5423
Name: sample_id, dtype: int64
sample_type
Buffer Negative Control (Extraction)            2662
Clinical Sample                               228027
Human Normal Negative Control (Extraction)      2665
Negative Control (qPCR)                         5539
Positive Control (qPCR)                         5192
Name: sample_id, dtype: int64

In [16]:
sample_gene = pd.read_hdf('./data/new_data.h5', key='igi_gene_call')
sample_gene.head(10)

  sample_id pcr_plate  target  igi_call      thres_ct
0   S053693  C302JKYE     MS2  Negative  Undetermined
1   S053693  C302JKYE  N gene  Negative  Undetermined
2   S053693  C302JKYE  ORF1ab  Negative  Undetermined
3   S053693  C302JKYE  S gene  Negative  Undetermined
4   S053683  C302JKYF     MS2  Positive    27.3529499
5   S053683  C302JKYF  N gene  Negative  Undetermined
6   S053683  C302JKYF  ORF1ab  Negative  Undetermined
7   S053683  C302JKYF  S gene  Negative  Undetermined
8   S053690  C302JKYE     MS2  Positive   29.27043094
9   S053690  C302JKYE  N gene  Negative  Undetermined

In [17]:
print('Number of sample_id in same gene:', sample_gene.sample_id.nunique())
print('Number of pcr_plate in same gene:', sample_gene.pcr_plate.nunique())
print(sample_gene.groupby('igi_call')[['sample_id','target']].count())

Number of sample_id in same gene: 302102
Number of pcr_plate in same gene: 1779
          sample_id  target
igi_call
#Error!          64      64
Negative     672816  672816
Positive     332495  332495

In [29]:
join_df = (curve_df # exclude pooled samples
    .merge(sample_info, how='inner', on=['well_position','pcr_plate'])
    .merge(sample_gene, how='inner', on=['pcr_plate','sample_id','target']))
join_df.head()

,well_position,target,dye,amp_score,cq,threshold,baseline_start,baseline_end,cycle_no,rn,...,sample_type,final_patient_result,current_sample_result,created_date,record_type,retest_sample_id_1,retest_sample_id_2,file,igi_call,thres_ct
0,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,1,13408.349609,...,Clinical Sample,Negative,Negative,4/27/21,Pooled Sample,NaN,NaN,db2a,Positive,24.674406947379367
1,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,2,13445.377930,...,Clinical Sample,Negative,Negative,4/27/21,Pooled Sample,NaN,NaN,db2a,Positive,24.674406947379367
2,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,3,13458.586914,...,Clinical Sample,Negative,Negative,4/27/21,Pooled Sample,NaN,NaN,db2a,Positive,24.674406947379367
3,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,4,13539.398438,...,Clinical Sample,Negative,Negative,4/27/21,Pooled Sample,NaN,NaN,db2a,Positive,24.674406947379367
4,A1,RnaseP,ATTO 647,2.503202,24.674406947379367,10000.0,3,15,5,13588.847656,...,Clinical Sample,Negative,Negative,4/27/21,Pooled Sample,NaN,NaN,db2a,Positive,24.674406947379367

In [20]:
print('join_df shape:', join_df.shape)
print('Number of pcr_plate in join_df:', join_df.pcr_plate.nunique())
print('Number of sample_id in join_df:', join_df.sample_id.nunique())
print('Number of curves in join_df:', join_df.curve_idx.nunique())

join_df shape: (33032145, 27)
Number of pcr_plate in join_df: 1201
Number of sample_id in join_df: 226445
Number of curves in join_df: 721684

In [23]:
curve_df_pcr_plate = curve_df.pcr_plate.unique()
sample_info_pcr_plate_unique = sample_info.pcr_plate.unique()

plate_not_in_sample_info = []
for plate in curve_df_pcr_plate:
    if plate not in sample_info_pcr_plate_unique:
        plate_not_in_sample_info.append(plate)

In [24]:
plate_not_in_sample_info

[]

In [31]:
join_df.groupby(['sample_type','current_sample_result']).curve_idx.nunique()

sample_type                                 current_sample_result
Buffer Negative Control (Extraction)        Invalid                      96
                                            Negative                   1432
Clinical Sample                             Inconclusive               8081
                                            Invalid                   25342
                                            Negative                 606111
                                            Positive                  40372
Human Normal Negative Control (Extraction)  Invalid                      96
                                            Negative                   1392
                                            Positive                     24
Negative Control (qPCR)                     Negative                  13418
Positive Control (qPCR)                     Positive                  12605
Name: curve_idx, dtype: int64

In [28]:
df = curve_df[curve_df.cycle_no == 1].groupby(['pcr_plate']).well_position.nunique().reset_index()
df.merge(sample_info.groupby('pcr_plate').well_position.nunique().reset_index(),
         on = 'pcr_plate')

     pcr_plate  well_position_x  well_position_y
0     AC00DANB              196              176
1     AC00DAND              384              100
2     AC00DANI              196              195
3     AC00DANO              384              383
4     AC00DANP              384              289
...        ...              ...              ...
1198  C302ST2C              384              195
1199  C302ST2D              196              196
1200  C302ST2E              196              195
1201  C302ST2F              196                3
1202  C302ST2G              196                1

[1203 rows x 3 columns]

In [36]:
groundtruth.groupby(['split','groundtruth']).curve_idx.nunique()

split  groundtruth
test   -1               623
        1              5552
train  -1              1481
        1             12468
val    -1               453
        1              4179
Name: curve_idx, dtype: int64