Notebook to generate data.h5 that includes curve_data, sample_info and igi_gene_call datasets

In [59]:
import os
import json
import glob
import pandas as pd
import numpy as np

In [39]:
DATA_DIR = '/Users/huongvu/Desktop/pcr/Data/New Data/'
CURVE_DIR = os.path.join(DATA_DIR, 'extracted_csv')
PRIMARY_DIR = os.path.join(DATA_DIR, 'primary_samples')
SIM_DIR = '/Users/huongvu/Desktop/PCR_simulation/'

In [40]:
sample_info = pd.read_csv(os.path.join(PRIMARY_DIR, 'sample_info.csv'))
sample_gene = pd.read_csv(os.path.join(PRIMARY_DIR, 'sample_gene.csv'))

In [41]:
sample_gene['rank'] = (sample_gene
                       .groupby(['sample_id','pcr_plate','target'])['thres_ct']
                       .rank(method='dense', ascending=False))
sample_gene = sample_gene.loc[sample_gene['rank'] == 1.0]
sample_gene = sample_gene.drop(labels='rank', axis=1)

In [42]:
sample_info['rank'] = (sample_info
                       .groupby(['sample_id','pcr_plate'])['created_date']
                       .rank(method='dense', ascending=False))
sample_info = sample_info.loc[sample_info['rank'] == 1.0]
sample_info = sample_info.drop(labels='rank', axis=1)

In [43]:
folders = os.listdir(CURVE_DIR)
folders.remove('.DS_Store')

amp_df = pd.DataFrame()
multcomp_df = pd.DataFrame()
da_result_df = pd.DataFrame()

error_files = {'amplification':[],
               'multicomponent':[],
               'da_result':[]}

In [44]:
for folder in folders:
    try: 
        df = pd.read_csv(os.path.join(CURVE_DIR, folder, 'Amplification Data.csv'))
        df = df.loc[:, ~df.columns.isin(['Well','Sample','Omit'])]
        df.columns = ['well_position','cycle_no','target','rn','drn']
        df.loc[:,'file'] = folder
        amp_df = pd.concat([amp_df, df],
                            ignore_index=True)
    except Exception as e:
        error_files['amplification'].append({'folder':folder,
                                          'msg': str(e)}) 
    
    try:
        df = pd.read_csv(os.path.join(CURVE_DIR, folder, 'Multicomponent.csv'))
        df = df.drop(columns='Well')
        df = (df.set_index(['Well Position','Cycle Number'])
                .melt(ignore_index=False)
                .reset_index())
        df.columns = ['well_position','cycle_no','dye','Fn']
        df.loc[:,'file'] = folder
        multcomp_df = pd.concat([multcomp_df, df],
                                ignore_index=True)
    except Exception as e:
        error_files['multicomponent'].append({'folder':folder,
                                          'msg': str(e)})

    try:
        df = pd.read_csv(os.path.join(CURVE_DIR, folder, 'Results.csv'))
        df = df[['Well Position','Target','Reporter','Amp Score','Cq',
                 'Threshold','Baseline Start','Baseline End']]
        df.columns = ['well_position','target','dye','amp_score','cq',
                      'threshold','baseline_start','baseline_end']
        df.loc[:,'file'] = folder
        da_result_df = pd.concat([da_result_df, df],
                                 ignore_index=True)
    except Exception as e:
        error_files['da_result'].append({'folder':folder,
                                          'msg': str(e)})

In [45]:
# check for error files
print(error_files)

{'amplification': [], 'multicomponent': [], 'da_result': []}

In [46]:
curve_df = (da_result_df
           .merge(amp_df, how = 'inner', on = ['well_position','file','target'])
           .merge(multcomp_df, how = 'inner', on = ['well_position','file','dye','cycle_no']))

file_dict = sample_info[['file','pcr_plate']].drop_duplicates().set_index('file').to_dict()['pcr_plate']
curve_df['pcr_plate'] = curve_df['file'].replace(file_dict)

curve_df['curve_idx'] = curve_df.groupby(['pcr_plate','target','well_position']).ngroup()
curve_df = curve_df.drop('file', axis = 1)

sample_info = sample_info.drop(sample_info[sample_info.pcr_plate == 'AC00DB15'].index, axis=0)
curve_df = curve_df.drop(curve_df[curve_df.pcr_plate == 'AC00DB15'].index, axis = 0)

Drop pcr_plate AC00GXWF, AC00DB6F, AC00H0OU because the whole plate is invalid

In [47]:
curve_df = curve_df.drop(curve_df[curve_df.pcr_plate.isin(['AC00GXWF','AC00DB6F','AC00H0OU'])].index, axis=0)
sample_info = sample_info.drop(sample_info[sample_info.pcr_plate.isin(['AC00GXWF','AC00DB6F','AC00H0OU'])].index, axis=0)
sample_gene = sample_gene.drop(sample_gene[sample_gene.pcr_plate.isin(['AC00GXWF','AC00DB6F','AC00H0OU'])].index, axis=0)

Drop sample_ids that are part of a pooled sample

In [48]:
sample_info = sample_info.drop(sample_info[sample_info.sample_id.isin(['S1268904', 'S1268905'])].index, axis=0)

impute current_sample_result for positive and negative control wells

In [50]:
sample_info.loc[sample_info.sample_type == 'Positive Control (qPCR)', 'current_sample_result'] = 'Positive'
sample_info.loc[sample_info.sample_type == 'Negative Control (qPCR)', 'current_sample_result'] = 'Negative'

impute Na retest sample id with np.nan

In [61]:
sample_info.loc[sample_info['retest_sample_id_1'] == ' ', 'retest_sample_id_1'] = np.nan
sample_info.loc[sample_info['retest_sample_id_2'] == ' ', 'retest_sample_id_2'] = np.nan

In [23]:
curve_df.to_hdf(os.path.join(SIM_DIR, 'data', 'data.h5'), key = 'curve_data', mode='w')
sample_info.to_hdf(os.path.join(SIM_DIR, 'data', 'data.h5'), key='sample_info')
sample_gene.to_hdf(os.path.join(SIM_DIR, 'data', 'data.h5'), key='igi_gene_call')

/opt/anaconda3/envs/pcr/lib/python3.8/site-packages/pandas/core/generic.py:2703: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block0_values] [items->Index(['sample_id', 'sample_barcode', 'pcr_plate', 'well_position',
       'sample_type', 'final_patient_result', 'current_sample_result',
       'created_date', 'record_type', 'retest_sample_id_1',
       'retest_sample_id_2', 'file'],
      dtype='object')]

  pytables.to_hdf(

In [63]:
join_df = (curve_df # exclude pooled samples
    .merge(sample_info, how='inner', on=['well_position','pcr_plate'])
    .merge(sample_gene, how='inner', on=['pcr_plate','sample_id','target']))
join_df.head()

,well_position,target,dye,amp_score,cq,threshold,baseline_start,baseline_end,cycle_no,rn,...,sample_type,final_patient_result,current_sample_result,created_date,record_type,retest_sample_id_1,retest_sample_id_2,file,igi_call,thres_ct
0,A1,S gene,ABY,0.0,Undetermined,8810.498,3,39,1,147103.828125,...,Clinical Sample,Negative,Negative,44205,Pooled Sample,NaN,NaN,db1i,Negative,Undetermined
1,A1,S gene,ABY,0.0,Undetermined,8810.498,3,39,2,146864.656250,...,Clinical Sample,Negative,Negative,44205,Pooled Sample,NaN,NaN,db1i,Negative,Undetermined
2,A1,S gene,ABY,0.0,Undetermined,8810.498,3,39,3,146410.109375,...,Clinical Sample,Negative,Negative,44205,Pooled Sample,NaN,NaN,db1i,Negative,Undetermined
3,A1,S gene,ABY,0.0,Undetermined,8810.498,3,39,4,146188.328125,...,Clinical Sample,Negative,Negative,44205,Pooled Sample,NaN,NaN,db1i,Negative,Undetermined
4,A1,S gene,ABY,0.0,Undetermined,8810.498,3,39,5,146078.421875,...,Clinical Sample,Negative,Negative,44205,Pooled Sample,NaN,NaN,db1i,Negative,Undetermined

In [52]:
join_df[(join_df.cycle_no == 1) & (join_df.current_sample_result == 'Invalid')].groupby('sample_type').count()

,well_position,target,dye,amp_score,cq,threshold,baseline_start,baseline_end,cycle_no,rn,...,sample_barcode,final_patient_result,current_sample_result,created_date,record_type,retest_sample_id_1,retest_sample_id_2,file,igi_call,thres_ct
sample_type,,,,,,,,,,,,,,,,,,,,,
Buffer Negative Control (Extraction),28,28,28,28,28,28,28,28,28,28,...,28,12,28,28,28,28,28,28,28,28
Clinical Sample,4118,4118,4118,4118,4118,4118,4118,4118,4118,4118,...,4118,3894,4118,4118,4118,4118,4118,4118,4118,4118
Human Normal Negative Control (Extraction),20,20,20,20,20,20,20,20,20,20,...,20,8,20,20,20,20,20,20,20,20

In [53]:
join_df.groupby(['sample_type', 'current_sample_result']).curve_idx.nunique()

sample_type                                 current_sample_result
Buffer Negative Control (Extraction)        Invalid                     28
                                            Negative                   228
Clinical Sample                             Inconclusive              1859
                                            Invalid                   4118
                                            Negative                 54338
                                            Positive                  5229
Human Normal Negative Control (Extraction)  Invalid                     20
                                            Negative                   236
Negative Control (qPCR)                     Negative                  1504
Positive Control (qPCR)                     Positive                  1504
Name: curve_idx, dtype: int64

In [54]:
join_df[(join_df.sample_type == 'Clinical Sample')].curve_idx.nunique()

65604

In [80]:
join_df[(join_df.current_sample_result == 'Inconclusive') & (join_df.cycle_no == 45) & (join_df.sample_type == 'Clinical Sample')].groupby(['sample_id']).count()

,well_position,target,dye,amp_score,cq,threshold,baseline_start,baseline_end,cycle_no,rn,drn,Fn,pcr_plate,curve_idx,sample_barcode,sample_type,final_patient_result,current_sample_result,created_date,record_type,retest_sample_id_1,retest_sample_id_2,file,igi_call,thres_ct
sample_id,,,,,,,,,,,,,,,,,,,,,,,,,
S1005189,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1005232,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1015907,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1016033,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1017975,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1018129,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1018703,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1019512,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1019514,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1019539,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1019566,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
S1020542,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1020547,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1020549,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1020554,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1020556,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1020557,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1020558,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1020560,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1020561,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1020562,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1026294,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1026588,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1026942,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1027378,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027379,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027380,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027381,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027382,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027386,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027387,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027389,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027390,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027391,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027393,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027395,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027396,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027397,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027401,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1027402,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1028001,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1029048,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1029072,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1029702,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1029706,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1031133,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1031141,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1031142,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1031146,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1031149,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1031182,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1031194,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1031201,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1031206,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1031208,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1032206,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1032251,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1032255,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1032265,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1034236,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1034538,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1034565,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1034570,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1034573,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1034574,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1034576,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1034582,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1034738,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1034755,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1034765,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1034773,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1034794,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1035105,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1035106,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1035122,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1035139,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1035732,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1035733,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1035766,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1061284,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061304,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061307,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061316,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061532,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061534,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061540,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061561,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061587,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061592,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061645,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061670,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061698,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061724,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1061733,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1075521,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1075537,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1075558,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1077003,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1077333,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1081677,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1081690,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1082765,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1082777,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1082779,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1087144,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1088669,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1088670,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1090528,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1090557,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1091153,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1091170,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1091185,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1091226,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1092536,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1092583,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1092609,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1096651,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1096683,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1096726,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1114186,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1114699,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1114700,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1116310,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1116318,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1116342,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1117778,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1118744,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1119113,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1119116,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1119126,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1119127,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1119178,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1119196,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1120042,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1120061,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1120104,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1120123,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1120679,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1120955,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1121023,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1121039,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1121230,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1121386,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1122443,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1122444,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1122486,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1122489,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1122613,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1123769,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1123772,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1123809,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1123961,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1124181,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
S1124197,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1124224,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1124277,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1124603,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1124657,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125002,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125160,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125162,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125167,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125176,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125188,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125196,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125201,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125214,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125221,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125224,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125453,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1125532,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1125535,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1125691,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1125694,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1126032,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1126067,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1126137,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1126162,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1126818,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1126834,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1134332,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1160160,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1163994,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
S1164009,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1164778,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1165105,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1165162,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1167202,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1170899,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1171966,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1172597,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1176365,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1176374,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1177402,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1178112,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1191950,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1192797,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1192798,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1192803,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1192822,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1193036,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1193085,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1193088,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1193161,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1193164,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1204384,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1204394,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1204408,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1204534,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1204815,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1204865,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1205642,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1205675,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1205814,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207003,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1207084,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207104,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207139,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207144,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207154,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207209,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207214,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207254,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207274,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207284,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207310,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207313,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207317,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207319,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207323,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207327,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207328,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207330,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207333,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207335,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207343,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207352,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207402,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207407,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207412,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207432,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207457,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207462,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1207473,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1207485,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1207492,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1207502,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1207506,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1207508,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1208028,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1208163,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1208465,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1209200,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1209215,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1209217,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1209231,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1209232,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1209234,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1209243,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1209244,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1210202,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1210226,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1210240,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1210248,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1210252,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1210258,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1210261,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1210268,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1210273,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1210275,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1210280,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1210346,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1212176,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1212883,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1212912,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1212950,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1213076,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1214254,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1214277,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1216409,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1221901,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1221932,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1221937,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1222325,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1223482,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1223521,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1231554,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1231850,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1260753,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1261902,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1262089,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1262095,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1262105,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1262107,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1262132,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1262195,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1262441,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1262905,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1262970,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1263012,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1263109,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1263459,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1263477,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1263969,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1263984,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1264002,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1264006,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1264215,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1264224,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1268883,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1270242,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1270261,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1270293,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1270329,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1270601,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1270630,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1270635,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1270673,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1306483,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1306541,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1306616,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1306632,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1309614,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S1309665,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
S1311449,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S1311450,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S455929,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S455982,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
S456885,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S623512,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S623768,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,3,3,3
S623823,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3
S623880,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,3,3,3

In [86]:
df = join_df[(join_df.current_sample_result == 'Inconclusive') & (join_df.sample_type == 'Clinical Sample') & (join_df.cycle_no == 45)].copy()
df['igi_call_encoded'] = [1 if x == 'Positive' else 0 for x in df['igi_call']]
df[df.target != 'RnaseP'].groupby('sample_id').igi_call_encoded.sum().count()
# join_df[(join_df.cycle_no == 45)].groupby('sample_id').agg(vote = ('igi_call', lambda x: sum(1 if x == 'Positive' else 0)))

405

In [84]:
df[df.sample_id.isin(['S993850'])]

,well_position,target,dye,amp_score,cq,threshold,baseline_start,baseline_end,cycle_no,rn,drn,Fn,pcr_plate,curve_idx,sample_id,sample_barcode,sample_type,final_patient_result,current_sample_result,created_date,record_type,retest_sample_id_1,retest_sample_id_2,file,igi_call,thres_ct,igi_call_encoded
1915094,K1,RnaseP,ATTO 647,2.604354,22.303629600783268,10000.0,3,14,45,341940.781250,311271.214714,341940.780,AC00GXZR,63616,S993850,SARS00016081,Clinical Sample,Negative,Inconclusive,12/16/21,Submitted Sample,SARS00016081- Retest 1,SARS00016081- Retest 2,gxzr,Positive,22.3036296,1
1915139,K1,E gene,VIC,0.000000,Undetermined,6000.0,3,44,45,217498.609375,597.350446,217498.610,AC00GXZR,62848,S993850,SARS00016081,Clinical Sample,Negative,Inconclusive,12/16/21,Submitted Sample,SARS00016081- Retest 1,SARS00016081- Retest 2,gxzr,Negative,Undetermined,0
1915184,K1,N gene,FAM,1.843257,33.39960587063479,11000.0,3,15,45,125533.304688,12495.643115,125533.305,AC00GXZR,63232,S993850,SARS00016081,Clinical Sample,Negative,Inconclusive,12/16/21,Submitted Sample,SARS00016081- Retest 1,SARS00016081- Retest 2,gxzr,Positive,33.39960587,1

In [74]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
join_df[(join_df.current_sample_result == 'Inconclusive') & (join_df.cycle_no == 45)]

        well_position  target       dye  amp_score                  cq  \
57504             G15  RnaseP  ATTO 647   2.645879  25.142049385208686
57549             G15  E gene       VIC   1.875754        Undetermined
57594             G15  N gene       FAM   2.083967  35.733493614036334
62364             M11  RnaseP  ATTO 647   2.636645   23.24589169430029
62409             M11  E gene       VIC   1.873418        Undetermined
62454             M11  N gene       FAM   2.165470   32.24727452491577
64929             O19  RnaseP  ATTO 647   0.000000        Undetermined
64974             O19  E gene       VIC   1.624481        Undetermined
65019             O19  N gene       FAM   2.033873   32.13139229330451
137154            M11  RnaseP  ATTO 647   2.486534  25.346094898141985
137199            M11  E gene       VIC   1.876453        Undetermined
137244            M11  N gene       FAM   2.017756   35.21801555351218
149979            I13  RnaseP  ATTO 647   2.260179  27.243500112415347
150024            I13  E gene       VIC   1.678567        Undetermined
150069            I13  N gene       FAM   1.882540  34.423362644690926
158889            A22  RnaseP  ATTO 647   2.592776   25.10723700456189
158934            A22  E gene       VIC   1.836696        Undetermined
158979            A22  N gene       FAM   1.984720   36.02595335146939
160644            C11  RnaseP  ATTO 647   2.584366  25.441771631915003
160689            C11  E gene       VIC   1.145469        Undetermined
160734            C11  N gene       FAM   2.373279  27.260958496630373
202899             M6  RnaseP  ATTO 647   2.385890  26.838818403889142
202944             M6  E gene       VIC   1.845647        Undetermined
202989             M6  N gene       FAM   2.304185   30.12730284289114
209649             A6  RnaseP  ATTO 647   2.607569  20.239712124394565
209694             A6  E gene       VIC   1.674279        Undetermined
209739             A6  N gene       FAM   2.096324   31.67267309337421
223014            O11  RnaseP  ATTO 647   2.170223   25.47559969672166
223059            O11  E gene       VIC   1.926361  29.927297435110383
223104            O11  N gene       FAM   0.000000        Undetermined
250554             A4  RnaseP  ATTO 647   2.577073  26.945073148891694
250599             A4  E gene       VIC   0.000000        Undetermined
250644             A4  N gene       FAM   2.182883   33.67782275451789
262569             M4  RnaseP  ATTO 647   2.563755  27.986904936094206
262614             M4  E gene       VIC   1.902477        Undetermined
262659             M4  N gene       FAM   2.375823  33.281066487418954
271479             G5  RnaseP  ATTO 647   2.454100   27.53543839436984
271524             G5  E gene       VIC   1.877851        Undetermined
271569             G5  N gene       FAM   2.282458  31.062317604703125
278499             O1  RnaseP  ATTO 647   2.386743  26.879526164864288
278544             O1  E gene       VIC   0.000000        Undetermined
278589             O1  N gene       FAM   2.133416  31.132162770058624
288084            E13  RnaseP  ATTO 647   2.650702   25.64189698083058
288129            E13  E gene       VIC   0.000000        Undetermined
288174            E13  N gene       FAM   2.671126   35.61395800585673
288894            E19  RnaseP  ATTO 647   2.639458  21.847421645747424
288939            E19  E gene       VIC   1.504619        Undetermined
288984            E19  N gene       FAM   2.417280   36.31826152461517
289839             G2  RnaseP  ATTO 647   2.625019  26.695529520357233
289884             G2  E gene       VIC   0.000000        Undetermined
289929             G2  N gene       FAM   2.326824   36.84715594742625
299694             M1  RnaseP  ATTO 647   2.575740  25.430216184759693
299739             M1  E gene       VIC   1.555274        Undetermined
299784             M1  N gene       FAM   1.941200   33.51172218670381
302799            M24  RnaseP  ATTO 647   2.633602  26.994447101126177
302844            M24  E gene       VIC   0.000000        Undetermined
302889            M24  N gene       FAM   1.989877   33.53801510064912
304014             O7  RnaseP  ATTO 647   2.633521  27.537740880014965
304059             O7  E gene       VIC   2.118147   37.18028838280662
304104             O7  N gene       FAM   2.476447     35.153077012745
305364            O17  RnaseP  ATTO 647   2.656725   23.30089377469605
305409            O17  E gene       VIC   1.532650        Undetermined
305454            O17  N gene       FAM   2.412078   36.49794421559183
346674            I13  RnaseP  ATTO 647   2.354058  26.371442042641362
346719            I13  E gene       VIC   0.000000        Undetermined
346764            I13  N gene       FAM   2.066373   32.46703903900024
349374             K9  RnaseP  ATTO 647   1.915794   32.78169061150848
349419             K9  E gene       VIC   0.000000        Undetermined
349464             K9  N gene       FAM   2.147317  30.908089747082457
349914            K13  RnaseP  ATTO 647   2.357576  26.020965286972796
349959            K13  E gene       VIC   1.718260        Undetermined
350004            K13  N gene       FAM   1.997248   32.50121612114143
356394            O11  RnaseP  ATTO 647   2.272113  26.582964541777912
356439            O11  E gene       VIC   1.789519        Undetermined
356484            O11  N gene       FAM   2.031252   31.97556885092342
475149            A24  RnaseP  ATTO 647   2.610588   26.75985538907976
475194            A24  E gene       VIC   1.784187        Undetermined
475239            A24  N gene       FAM   2.281063  33.234858264445975
476904            B13  RnaseP  ATTO 647   2.654759   23.39099176082376
476949            B13  E gene       VIC   1.540972        Undetermined
476994            B13  N gene       FAM   2.123393  36.903755158218544
482169             D9  RnaseP  ATTO 647   2.606719    27.6740414072527
482214             D9  E gene       VIC   1.916056        Undetermined
482259             D9  N gene       FAM   2.164428   36.98650013319114
483384            D21  RnaseP  ATTO 647   2.623176  26.918126342869833
483429            D21  E gene       VIC   1.815814        Undetermined
483474            D21  N gene       FAM   2.177431   34.58219341716741
498234            I23  RnaseP  ATTO 647   2.717059   26.72111977307106
498279            I23  E gene       VIC   2.050564        Undetermined
498324            I23  N gene       FAM   2.278638   35.35550509559112
498369            I24  RnaseP  ATTO 647   2.037110   35.87125308893945
498414            I24  E gene       VIC   2.218910   36.48473674377818
498459            I24  N gene       FAM   0.000000        Undetermined
518079             A1  RnaseP  ATTO 647   2.530387  27.156603484531708
518124             A1  E gene       VIC   1.648733        Undetermined
518169             A1  N gene       FAM   2.144936   34.78124134115175
518214             A3  RnaseP  ATTO 647   2.570951   23.66626607995024
518259             A3  E gene       VIC   1.386023        Undetermined
518304             A3  N gene       FAM   2.138660   34.49036448753693
518484             A7  RnaseP  ATTO 647   2.546627  27.597382812056274
518529             A7  E gene       VIC   1.496066        Undetermined
518574             A7  N gene       FAM   2.143190   35.14934509157458
518619             A9  RnaseP  ATTO 647   2.582865   26.48460296215017
518664             A9  E gene       VIC   1.171458        Undetermined
518709             A9  N gene       FAM   2.061786   36.06049201071198
518889            A13  RnaseP  ATTO 647   2.506569  26.904111264966396
518934            A13  E gene       VIC   0.000000        Undetermined
518979            A13  N gene       FAM   1.935390   36.58260884691375
519159            A17  RnaseP  ATTO 647   2.573576  27.112776369238098
519204            A17  E gene       VIC   1.340040        Undetermined
519249            A17  N gene       FAM   2.179651   35.29940312142788
519699             C1  RnaseP  ATTO 647   2.527225  27.155554448560274
519744             C1  E gene       VIC   1.726967        Undetermined
519789             C1  N gene       FAM   2.250786   33.81597819015007
519969             C5  RnaseP  ATTO 647   2.584282   25.70610846216053
520014             C5  E gene       VIC   1.795045   39.02862859343688
520059             C5  N gene       FAM   2.248027   34.85427652436421
520104             C7  RnaseP  ATTO 647   2.580352  26.749180989703554
520149             C7  E gene       VIC   0.000000        Undetermined
520194             C7  N gene       FAM   2.040996   35.78661392071661
520779            C17  RnaseP  ATTO 647   2.615139  21.370484091446855
520824            C17  E gene       VIC   1.433010        Undetermined
520869            C17  N gene       FAM   2.128798  34.273970552503386
520914            C19  RnaseP  ATTO 647   2.553886   28.28335597124444
520959            C19  E gene       VIC   1.572749        Undetermined
521004            C19  N gene       FAM   2.063735   36.10581365387788
521184            C23  RnaseP  ATTO 647   2.530101   28.14427623179221
521229            C23  E gene       VIC   1.479662        Undetermined
521274            C23  N gene       FAM   2.159509   35.35073859821222
521319             E1  RnaseP  ATTO 647   2.562457   25.85936823533411
521364             E1  E gene       VIC   0.000000        Undetermined
521409             E1  N gene       FAM   2.198459   35.39049443474865
522399            E17  RnaseP  ATTO 647   2.579480  26.966080708659327
522444            E17  E gene       VIC   0.000000        Undetermined
522489            E17  N gene       FAM   2.028755   36.11765272063541
522669            E21  RnaseP  ATTO 647   2.572277  27.186037820799086
522714            E21  E gene       VIC   0.000000        Undetermined
522759            E21  N gene       FAM   2.020732  36.076898633562756
522804            E23  RnaseP  ATTO 647   2.564340  27.154626706467738
522849            E23  E gene       VIC   0.000000        Undetermined
522894            E23  N gene       FAM   2.102547    35.6693774149779
523074             G3  RnaseP  ATTO 647   2.550056  27.419519736371207
523119             G3  E gene       VIC   1.727633        Undetermined
523164             G3  N gene       FAM   2.183968  34.960643965304776
523749            G11  RnaseP  ATTO 647   2.594876  27.037757687774963
523794            G11  E gene       VIC   1.629281        Undetermined
523839            G11  N gene       FAM   2.221516  35.070760261017085
524289            G19  RnaseP  ATTO 647   2.590082  24.773940739023345
524334            G19  E gene       VIC   1.605092        Undetermined
524379            G19  N gene       FAM   2.087355    35.4348134550625
524559            G23  RnaseP  ATTO 647   2.568364  26.420262447676123
524604            G23  E gene       VIC   0.000000        Undetermined
524649            G23  N gene       FAM   2.058198   36.16843469310235
524964             I1  RnaseP  ATTO 647   2.562360   26.59523606111523
525009             I1  E gene       VIC   1.650525        Undetermined
525054             I1  N gene       FAM   2.029633  34.591624239078214
525369             I7  RnaseP  ATTO 647   2.553436  27.165314851773196
525414             I7  E gene       VIC   1.723684        Undetermined
525459             I7  N gene       FAM   2.139907   35.77951198864031
526179            I19  RnaseP  ATTO 647   2.514561  28.432501750481805
526224            I19  E gene       VIC   1.667443        Undetermined
526269            I19  N gene       FAM   2.121580   35.33348434412852
526449            I23  RnaseP  ATTO 647   2.595645  28.066547349908085
526494            I23  E gene       VIC   1.750065        Undetermined
526539            I23  N gene       FAM   2.130850   35.89684526036624
526584             K1  RnaseP  ATTO 647   2.553091  26.525012315858305
526629             K1  E gene       VIC   1.690911        Undetermined
526674             K1  N gene       FAM   1.993195   36.59604613347236
527529            K15  RnaseP  ATTO 647   2.593382   26.40321062772521
527574            K15  E gene       VIC   0.000000        Undetermined
527619            K15  N gene       FAM   2.051738  35.781635626815294
527664            K17  RnaseP  ATTO 647   2.575825  27.454636598193346
527709            K17  E gene       VIC   0.000000        Undetermined
527754            K17  N gene       FAM   2.087525   36.28590370391672
527799            K19  RnaseP  ATTO 647   2.568032  26.808452912113857
527844            K19  E gene       VIC   0.000000        Undetermined
527889            K19  N gene       FAM   2.090834  36.946738992570225
530229             O1  RnaseP  ATTO 647   2.509217  25.945571576688877
530274             O1  E gene       VIC   1.320512        Undetermined
530319             O1  N gene       FAM   1.876639   36.57354059908124
530364             O3  RnaseP  ATTO 647   2.546655  27.161837947260878
530409             O3  E gene       VIC   1.703197        Undetermined
530454             O3  N gene       FAM   2.186234   36.47912668752376
530634             O7  RnaseP  ATTO 647   2.576902   26.03520626096754
530679             O7  E gene       VIC   1.636593        Undetermined
530724             O7  N gene       FAM   2.158136    34.6273997366951
530769             O9  RnaseP  ATTO 647   2.555782  26.844877270427197
530814             O9  E gene       VIC   1.671992        Undetermined
530859             O9  N gene       FAM   2.073876  35.616022009192086
531174            O15  RnaseP  ATTO 647   2.586349  25.613758144472726
531219            O15  E gene       VIC   1.311697        Undetermined
531264            O15  N gene       FAM   2.089171   34.94224403386191
536304            C11  RnaseP  ATTO 647   2.664551   21.27828539159995
536349            C11  E gene       VIC   0.000000        Undetermined
536394            C11  N gene       FAM   2.435147  22.044484094500866
599619            C11  RnaseP  ATTO 647   2.666515  23.448357222799217
599664            C11  E gene       VIC   0.000000        Undetermined
599709            C11  N gene       FAM   2.430535   24.54574669805755
611229             A2  RnaseP  ATTO 647   2.579157   25.91638198087685
611274             A2  E gene       VIC   1.912444  26.482373890895595
611319             A2  N gene       FAM   1.962926  25.532970374335488
613794            A22  RnaseP  ATTO 647   2.747780  17.932070169186495
613839            A22  E gene       VIC   1.607306        Undetermined
613884            A22  N gene       FAM   1.815597        Undetermined
621759            E16  RnaseP  ATTO 647   2.569348   25.84769119198856
621804            E16  E gene       VIC   1.476264        Undetermined
621849            E16  N gene       FAM   2.239201   28.68143383052901
631209            I23  RnaseP  ATTO 647   2.613154   19.81697607209079
631254            I23  E gene       VIC   0.000000        Undetermined
631299            I23  N gene       FAM   2.124968   23.15546678809639
631884             J7  RnaseP  ATTO 647   2.543603  24.034151819241664
631929             J7  E gene       VIC   1.646655        Undetermined
631974             J7  N gene       FAM   2.199551   25.73707185756433
646194             A8  RnaseP  ATTO 647   2.624510  20.728364178336683
646239             A8  E gene       VIC   0.000000        Undetermined
646284             A8  N gene       FAM   2.049632  36.700809715515916
649029             C5  RnaseP  ATTO 647   2.626631  21.487362372995058
649074             C5  E gene       VIC   1.517996        Undetermined
649119             C5  N gene       FAM   2.327877   36.01833510853503
655239             G3  RnaseP  ATTO 647   2.603449  23.403051058351153
655284             G3  E gene       VIC   1.404775        Undetermined
655329             G3  N gene       FAM   2.125454   36.52535214865873
657669            G21  RnaseP  ATTO 647   2.622816   23.28977240497487
657714            G21  E gene       VIC   0.000000        Undetermined
657759            G21  N gene       FAM   2.348490    36.4130920396705
658074            G24  RnaseP  ATTO 647   2.570945  25.963427999501086
658119            G24  E gene       VIC   1.280028        Undetermined
658164            G24  N gene       FAM   2.511786   36.19597913346678
659559             I9  RnaseP  ATTO 647   2.627145  24.129466451185174
659604             I9  E gene       VIC   0.000000        Undetermined
659649             I9  N gene       FAM   2.549771   35.09861217889508
659829            I11  RnaseP  ATTO 647   2.629224  23.190073856540053
659874            I11  E gene       VIC   0.000000        Undetermined
659919            I11  N gene       FAM   2.399853   36.70596358523228
660369            I15  RnaseP  ATTO 647   2.633958  22.741306278152834
660414            I15  E gene       VIC   2.147286    36.6599902217219
660459            I15  N gene       FAM   1.208943        Undetermined
661449            I23  RnaseP  ATTO 647   2.591449   25.06025884348201
661494            I23  E gene       VIC   1.600799        Undetermined
661539            I23  N gene       FAM   2.673462   34.79663741049892
661584            I24  RnaseP  ATTO 647   2.602926   25.54487472856114
661629            I24  E gene       VIC   0.000000        Undetermined
661674            I24  N gene       FAM   2.582731    35.4161204272357
662664             K8  RnaseP  ATTO 647   2.646781  22.966118653785387
662709             K8  E gene       VIC   1.455162        Undetermined
662754             K8  N gene       FAM   2.254054   36.52065171763022
664959             M1  RnaseP  ATTO 647   2.583886   23.97730323874736
665004             M1  E gene       VIC   0.000000        Undetermined
665049             M1  N gene       FAM   1.927019   32.62665884316842
665634             M6  RnaseP  ATTO 647   2.636686  21.719794012587514
665679             M6  E gene       VIC   0.000000        Undetermined
665724             M6  N gene       FAM   2.291289   35.84853114172074
665769             M7  RnaseP  ATTO 647   2.628039  22.138272465005258
665814             M7  E gene       VIC   1.950543   41.70596100907517
665859             M7  N gene       FAM   2.330271   35.28281616495618
669549             O9  RnaseP  ATTO 647   2.624466   23.48548675852191
669594             O9  E gene       VIC   1.386298        Undetermined
669639             O9  N gene       FAM   2.428602   35.11444113016542
681834             M1  RnaseP  ATTO 647   2.572762  25.106071248329584
681879             M1  E gene       VIC   0.000000        Undetermined
681924             M1  N gene       FAM   1.920088  32.787826886165604
688179            A21  RnaseP  ATTO 647   2.592295  27.372286069281138
688224            A21  E gene       VIC   0.000000        Undetermined
688269            A21  N gene       FAM   2.235436  35.644476905780124
688314            A22  RnaseP  ATTO 647   2.598853  27.189723069335088
688359            A22  E gene       VIC   0.000000        Undetermined
688404            A22  N gene       FAM   2.225237  35.115316728263934
697089            E19  RnaseP  ATTO 647   2.604025  23.726241359174303
697134            E19  E gene       VIC   0.000000        Undetermined
697179            E19  N gene       FAM   2.191368  35.608618866735426
699384             G2  RnaseP  ATTO 647   2.581108     24.281497244412
699429             G2  E gene       VIC   2.007905    36.7097377972149
699474             G2  N gene       FAM   2.227195   36.63005108016611
702084            G22  RnaseP  ATTO 647   2.588754  26.269740999367762
702129            G22  E gene       VIC   2.234374   36.36625769141575
702174            G22  N gene       FAM   1.692056        Undetermined
708159            J19  RnaseP  ATTO 647   2.615246  27.021984515063288
708204            J19  E gene       VIC   0.000000        Undetermined
708249            J19  N gene       FAM   2.298214   35.91805409176173
711264            K21  RnaseP  ATTO 647   2.583331  23.522820463501894

In [87]:
join_df.pcr_plate.nunique()

115

In [107]:

df = join_df[(join_df.sample_type == 'Buffer Negative Control (Extraction)') & (join_df.cycle_no == 1)]
df['igi_call_encoded'] = [1 if x == 'Positive' else 0 for x in df['igi_call']]
df1 = df.groupby('sample_id').igi_call_encoded.sum().reset_index()
df1[df1.igi_call_encoded > 0].shape

/var/folders/q4/trxghvfn21sdx12kbtpt92n00000gn/T/ipykernel_57387/3698874662.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['igi_call_encoded'] = [1 if x == 'Positive' else 0 for x in df['igi_call']]

(61, 2)

In [120]:
control_gene_ids = (join_df
                    .loc[join_df.retest_sample_id_1.isna()]
 .loc[join_df.cycle_no == 1]
 .loc[join_df.target.isin(['RnaseP', 'MS2'])]).curve_idx.unique()

other_ground_truth = (join_df
                      .loc[join_df.retest_sample_id_1.isna()]
 .loc[~join_df.target.isin(['RnaseP','MS2'])]
 .loc[join_df.sample_type != 'Clinical Sample']).curve_idx.unique()

In [121]:
len(np.concatenate([control_gene_ids, other_ground_truth]))

23671

In [122]:
(join_df[join_df.curve_idx.isin(list(np.concatenate([control_gene_ids, other_ground_truth])))]
 .groupby(['sample_type','igi_call','target'])
 .curve_idx
 .nunique())

sample_type                                 igi_call  target
Buffer Negative Control (Extraction)        Negative  E gene      169
                                                      MS2           6
                                                      N gene      232
                                                      ORF1ab       64
                                                      RnaseP      166
                                                      S gene       64
                                            Positive  MS2          58
                                                      N gene        1
                                                      RnaseP        3
Clinical Sample                             Negative  MS2         134
                                                      RnaseP      403
                                            Positive  MS2        4593
                                                      RnaseP    14004
Human Normal Negative Control (Extraction)  Negative  E gene      170
                                                      MS2           4
                                                      N gene      233
                                                      ORF1ab       64
                                                      RnaseP        3
                                                      S gene       64
                                            Positive  MS2          60
                                                      N gene        1
                                                      RnaseP      167
Negative Control (qPCR)                     Negative  E gene      324
                                                      MS2         133
                                                      N gene      457
                                                      ORF1ab      133
                                                      RnaseP      324
                                                      S gene      132
                                            Positive  S gene        1
Positive Control (qPCR)                     Negative  E gene        1
                                                      MS2         133
                                                      RnaseP      324
                                            Positive  E gene      323
                                                      N gene      457
                                                      ORF1ab      133
                                                      S gene      133
Name: curve_idx, dtype: int64

In [127]:
control_gene_ids = (join_df
                    .loc[(~join_df.retest_sample_id_1.isna()) & (join_df.retest_sample_id_2.isna())]
 .loc[join_df.cycle_no == 1]
 .loc[join_df.target.isin(['RnaseP', 'MS2'])]).curve_idx.unique()

other_ground_truth = (join_df
                      .loc[(~join_df.retest_sample_id_1.isna()) & (join_df.retest_sample_id_2.isna())]
 .loc[~join_df.target.isin(['RnaseP','MS2'])]
 .loc[join_df.sample_type != 'Clinical Sample']).curve_idx.unique()

(join_df[join_df.curve_idx.isin(list(np.concatenate([control_gene_ids, other_ground_truth])))]
 .groupby(['sample_type','final_patient_result','current_sample_result'])
 .sample_id
 .nunique())

sample_type      final_patient_result  current_sample_result
Clinical Sample  Negative              Inconclusive             235
                                       Invalid                  549
                                       Negative                   6
                 Positive              Inconclusive              56
                                       Invalid                   47
                                       Positive                   1
                 ReSample              Inconclusive               9
                                       Invalid                   13
Name: sample_id, dtype: int64

In [128]:
control_gene_ids = (join_df
                    .loc[(~join_df.retest_sample_id_1.isna()) & (~join_df.retest_sample_id_2.isna())]
 .loc[join_df.cycle_no == 1]
 .loc[join_df.target.isin(['RnaseP', 'MS2'])]).curve_idx.unique()

other_ground_truth = (join_df
                      .loc[(~join_df.retest_sample_id_1.isna()) & (~join_df.retest_sample_id_2.isna())]
 .loc[~join_df.target.isin(['RnaseP','MS2'])]
 .loc[join_df.sample_type != 'Clinical Sample']).curve_idx.unique()

(join_df[join_df.curve_idx.isin(list(np.concatenate([control_gene_ids, other_ground_truth])))]
 .groupby(['sample_type','final_patient_result','current_sample_result'])
 .sample_id
 .nunique())

sample_type      final_patient_result  current_sample_result
Clinical Sample  Negative              Inconclusive             21
                                       Invalid                  74
                                       Negative                  1
                 Positive              Inconclusive              2
                                       Invalid                   3
                                       Negative                  1
                 ReSample              Inconclusive              1
                                       Invalid                  14
Name: sample_id, dtype: int64