In [1]:
import pandas as pd

In [42]:
curve_df = pd.read_hdf('./data/data.h5', key='curve_data')
sample_info = pd.read_hdf('./data/data.h5', key='sample_info')
igi_gene_call = pd.read_hdf('./data/data.h5', key='igi_gene_call')

In [19]:
curve_df.loc[:,'rounded_cq'] = [int(float(x)) if x != 'Undetermined' else x for x in curve_df.cq]
fn_threshold_df = (curve_df
                    .loc[curve_df.cycle_no == curve_df.rounded_cq, ['curve_idx','cycle_no','cq', 'Fn']]
                    .rename(columns={'Fn':'fn_threshold'}))
fn_threshold_df.loc[:,'fn_low'] = fn_threshold_df.fn_threshold - 0.05*fn_threshold_df.fn_threshold
fn_threshold_df.loc[:,'fn_high'] = fn_threshold_df.fn_threshold + 0.05*fn_threshold_df.fn_threshold

In [56]:
std_df = (curve_df
    .loc[(curve_df.cycle_no <= curve_df.baseline_end)]
    .groupby(['pcr_plate','target'])
    .Fn.std().reset_index())

std_df.loc[:,'fn_threshold'] = std_df.Fn*10
std_df.loc[:,'fn_low1'] = std_df.fn_threshold - 0.05*std_df.fn_threshold
std_df.loc[:,'fn_high1'] = std_df.fn_threshold + 0.05*std_df.fn_threshold
std_df = std_df.drop('Fn', axis = 1)

In [ ]:
threshold_df = curve_df[['curve_idx','cq','threshold']].drop_duplicates()
threshold_df.loc[:,'drn_low'] = threshold_df.threshold - 0.05*threshold_df.threshold
threshold_df.loc[:,'drn_high'] = threshold_df.threshold + 0.05*threshold_df.threshold

In [10]:
max_cycle_df = curve_df.groupby(['curve_idx']).cycle_no.agg(max).reset_index()
luner_ids = max_cycle_df[max_cycle_df.cycle_no == 45].curve_idx.unique()
thermo_ids = max_cycle_df[max_cycle_df.cycle_no == 40].curve_idx.unique()

In [62]:
join_df = (curve_df
          .merge(threshold_df[['curve_idx','drn_low','drn_high']], how = 'inner', on = 'curve_idx')
          .merge(fn_threshold_df[['curve_idx','fn_threshold','fn_low','fn_high']], how = 'inner', on = 'curve_idx')
          .merge(std_df, how='inner', on = ['pcr_plate', 'target']))

In [63]:
amb_df = (join_df
            .loc[((join_df.curve_idx.isin(luner_ids)) & (join_df.cycle_no >= 40)) | 
                        ((join_df.curve_idx.isin(thermo_ids)) & (join_df.cycle_no >= 35))]
           .loc[(join_df.drn <= join_df.drn_high) & (join_df.drn >= join_df.drn_low)])
amb_df.curve_idx.nunique()

653

In [64]:
amb_df = (join_df
            .loc[((join_df.curve_idx.isin(luner_ids)) & (join_df.cycle_no >= 40)) | 
                        ((join_df.curve_idx.isin(thermo_ids)) & (join_df.cycle_no >= 35))]
           .loc[(join_df.Fn <= join_df.fn_high1) & (join_df.Fn >= join_df.fn_low1)])
amb_df.curve_idx.nunique()

1375

In [65]:
amb_df[['curve_idx','cq','threshold','cycle_no','Fn','drn','drn_low','drn_high','fn_low','fn_high']]

,curve_idx,cq,threshold,cycle_no,Fn,drn,drn_low,drn_high,fn_low,fn_high
37,23616,26.07906497442115,4189.194,38,245175.600,87377.637664,3979.7343,4398.6537,154587.344,170859.696
38,23616,26.07906497442115,4189.194,39,254079.900,96350.501069,3979.7343,4398.6537,154587.344,170859.696
39,23616,26.07906497442115,4189.194,40,261890.660,104229.801974,3979.7343,4398.6537,154587.344,170859.696
74,23627,23.57513092064245,4189.194,35,247405.310,20829.281771,3979.7343,4398.6537,219642.356,242762.604
75,23627,23.57513092064245,4189.194,36,249982.470,23503.192708,3979.7343,4398.6537,219642.356,242762.604
...,...,...,...,...,...,...,...,...,...,...
1194835,128498,39.721298219723636,18212.000,36,122166.740,10401.619216,17301.4000,19122.6000,122710.360,135627.240
1195074,128494,39.95485111707075,18212.000,35,112587.490,5158.835793,17301.4000,19122.6000,117476.202,129842.118
1195075,128494,39.95485111707075,18212.000,36,114994.950,7425.602628,17301.4000,19122.6000,117476.202,129842.118
1195076,128494,39.95485111707075,18212.000,37,117643.336,9933.291338,17301.4000,19122.6000,117476.202,129842.118
1195077,128494,39.95485111707075,18212.000,38,120858.850,13008.112861,17301.4000,19122.6000,117476.202,129842.118

In [67]:
join_df.loc[join_df.curve_idx == 23616,['curve_idx','pcr_plate','target','well_position','cq','threshold','cycle_no','Fn','drn','drn_low','drn_high','fn_low','fn_high', 'fn_low1','fn_high1']]

,curve_idx,pcr_plate,target,well_position,cq,threshold,cycle_no,Fn,drn,drn_low,drn_high,fn_low,fn_high,fn_low1,fn_high1
0,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,1,160733.60,399.254194,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
1,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,2,160684.52,418.726974,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
2,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,3,160373.90,176.668503,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
3,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,4,160091.80,-36.889967,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
4,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,5,160030.38,-29.760937,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
5,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,6,160304.42,312.836842,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
6,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,7,160208.56,285.528372,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
7,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,8,159773.53,-80.951974,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
8,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,9,159597.06,-188.869819,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
9,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,10,159549.60,-167.787664,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
10,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,11,159534.47,-114.361760,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
11,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,12,159692.78,112.501645,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
12,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,13,159511.02,-0.713076,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
13,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,14,159295.58,-147.599671,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
14,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,15,158891.80,-482.830016,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
15,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,16,158872.03,-434.044737,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
16,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,17,159176.10,-61.431332,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
17,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,18,159223.61,54.635197,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
18,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,19,159306.55,206.123602,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
19,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,20,159336.45,304.580757,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
20,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,21,159255.69,292.366036,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
21,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,22,159261.25,366.479441,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
22,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,23,159667.11,840.889720,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
23,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,24,160240.92,1483.253125,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
24,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,25,160899.48,2210.366530,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
25,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,26,162723.52,4102.948684,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
26,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,27,165097.50,6545.483964,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
27,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,28,168382.34,9898.878618,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
28,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,29,173005.00,14590.085773,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
29,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,30,178381.94,20035.574178,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
30,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,31,185353.48,27075.671957,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
31,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,32,192276.69,34067.425987,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
32,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,33,199760.88,41620.164391,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
33,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,34,208293.31,50221.152796,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
34,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,35,216972.53,58968.922451,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
35,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,36,226034.16,68099.098355,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
36,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,37,235684.94,77818.430510,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
37,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,38,245175.60,87377.637664,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
38,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,39,254079.90,96350.501069,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143
39,23616,AC00DB1I,MS2,A1,26.07906497442115,4189.194,40,261890.66,104229.801974,3979.7343,4398.6537,154587.344,170859.696,240075.261034,265346.341143

In [43]:
comprehensive_df = (amb_df
                    .merge(sample_info, how='inner', on=['well_position','pcr_plate'])
                    .merge(igi_gene_call, how='inner', on=['pcr_plate','sample_id','target']))

In [44]:
(comprehensive_df
    .groupby(['sample_type','igi_call','target'])
    .curve_idx
    .nunique())

sample_type                                 igi_call  target
Buffer Negative Control (Extraction)        Negative  E gene      6
                                                      N gene      1
                                                      ORF1ab      1
                                                      RnaseP      1
                                                      S gene      1
                                            Positive  MS2         1
Clinical Sample                             Negative  E gene     84
                                                      MS2        21
                                                      N gene    110
                                                      ORF1ab     28
                                                      RnaseP     44
                                                      S gene     61
                                            Positive  MS2        58
                                                      N gene     30
                                                      ORF1ab     16
                                                      S gene     20
Human Normal Negative Control (Extraction)  Negative  E gene      4
                                                      N gene      5
                                                      ORF1ab      1
                                                      S gene      1
                                            Positive  MS2         1
Negative Control (qPCR)                     Negative  E gene      7
                                                      MS2         1
                                                      N gene      1
                                                      RnaseP      1
                                                      S gene      3
Positive Control (qPCR)                     Negative  MS2         3
                                                      RnaseP      1
                                            Positive  ORF1ab      3
                                                      S gene      6
Name: curve_idx, dtype: int64

In [76]:
import numpy as np
curve_df.loc[curve_df.pcr_plate == 'AC00DB1I'].groupby('target').agg(threshold = ('drn', lambda x: np.std(x)))

            threshold
target
MS2      64001.557309
N gene   73400.615725
ORF1ab  100427.488225
S gene   87461.373275