In [3]:
import pandas as pd

In [4]:
curve_df = pd.read_hdf('../data/data.h5', key='curve_data')
sample_info = pd.read_hdf('../data/data.h5', key='sample_info')
igi_gene_call = pd.read_hdf('../data/data.h5', key='igi_gene_call')

join_df = (curve_df
           .merge(sample_info, how='inner', on=['well_position','pcr_plate'])
           .merge(igi_gene_call, how ='inner', on=['pcr_plate','sample_id','target']))

In [5]:
retest_df = (join_df[(join_df.retest_sample_id_1 != ' ')]) # & (~join_df.target.isin(['MS2','RnaseP']))])

# retest_df.to_csv('../data/retest_df.csv', index=False)

In [7]:
(retest_df.groupby('final_patient_result').sample_id.nunique())

final_patient_result
Negative    1062
Positive     137
ReSample      37
Name: sample_id, dtype: int64

In [22]:
(retest_df)

,well_position,target,dye,amp_score,cq,threshold,baseline_start,baseline_end,cycle_no,rn,drn,Fn,pcr_plate,curve_idx,sample_id,sample_barcode,sample_type,final_patient_result,current_sample_result,created_date,record_type,retest_sample_id_1,retest_sample_id_2,file,igi_call,thres_ct,orig_sample_id
57460,G15,RnaseP,ATTO 647,2.645879,25.142049385208686,10000.0,3,17,1,25551.169922,88.106796,25551.170,AC00GY8Y,71590,S1075558,SARS00035536,Clinical Sample,Negative,Inconclusive,1/21/22,Submitted Sample,SARS00035536- Retest 1,,gy8y,Positive,25.14204939,SARS00035536
57461,G15,RnaseP,ATTO 647,2.645879,25.142049385208686,10000.0,3,17,2,25615.337891,80.322693,25615.338,AC00GY8Y,71590,S1075558,SARS00035536,Clinical Sample,Negative,Inconclusive,1/21/22,Submitted Sample,SARS00035536- Retest 1,,gy8y,Positive,25.14204939,SARS00035536
57462,G15,RnaseP,ATTO 647,2.645879,25.142049385208686,10000.0,3,17,3,25755.812500,148.845231,25755.812,AC00GY8Y,71590,S1075558,SARS00035536,Clinical Sample,Negative,Inconclusive,1/21/22,Submitted Sample,SARS00035536- Retest 1,,gy8y,Positive,25.14204939,SARS00035536
57463,G15,RnaseP,ATTO 647,2.645879,25.142049385208686,10000.0,3,17,4,25863.421875,184.502534,25863.422,AC00GY8Y,71590,S1075558,SARS00035536,Clinical Sample,Negative,Inconclusive,1/21/22,Submitted Sample,SARS00035536- Retest 1,,gy8y,Positive,25.14204939,SARS00035536
57464,G15,RnaseP,ATTO 647,2.645879,25.142049385208686,10000.0,3,17,5,25645.996094,-104.875319,25645.996,AC00GY8Y,71590,S1075558,SARS00035536,Clinical Sample,Negative,Inconclusive,1/21/22,Submitted Sample,SARS00035536- Retest 1,,gy8y,Positive,25.14204939,SARS00035536

In [24]:
sum(retest_df['orig_sample_id'] != retest_df['sample_barcode'])

0

In [23]:
(retest_df
.merge(retest_df, left_on = 'retest_sample_id_1', right_on = 'sample_barcode'))

Empty DataFrame
Columns: [well_position_x, target_x, dye_x, amp_score_x, cq_x, threshold_x, baseline_start_x, baseline_end_x, cycle_no_x, rn_x, drn_x, Fn_x, pcr_plate_x, curve_idx_x, sample_id_x, sample_barcode_x, sample_type_x, final_patient_result_x, current_sample_result_x, created_date_x, record_type_x, retest_sample_id_1_x, retest_sample_id_2_x, file_x, igi_call_x, thres_ct_x, orig_sample_id_x, well_position_y, target_y, dye_y, amp_score_y, cq_y, threshold_y, baseline_start_y, baseline_end_y, cycle_no_y, rn_y, drn_y, Fn_y, pcr_plate_y, curve_idx_y, sample_id_y, sample_barcode_y, sample_type_y, final_patient_result_y, current_sample_result_y, created_date_y, record_type_y, retest_sample_id_1_y, retest_sample_id_2_y, file_y, igi_call_y, thres_ct_y, orig_sample_id_y]
Index: []

In [10]:
retest_df.curve_idx.nunique()

2848

In [4]:
df = (retest_df[retest_df.cycle_no == 1]
.groupby('sample_id')
.curve_idx.nunique().reset_index())

In [6]:

df[~df.curve_idx.isin([3,4])]

Empty DataFrame
Columns: [sample_id, curve_idx]
Index: []